In [6]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler, MaxAbsScaler, QuantileTransformer
from joblib import dump

In [4]:
df_data = pd.read_csv("../results/2_check_outliers.csv")
df_data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,is_isolated,is_lof
0,6,148.0,72.0,35.00000,155.548223,33.6,0.627,50,1,1,1
1,1,85.0,66.0,29.00000,155.548223,26.6,0.351,31,0,1,1
2,8,183.0,64.0,29.15342,155.548223,23.3,0.672,32,1,1,1
3,1,89.0,66.0,23.00000,94.000000,28.1,0.167,21,0,1,1
4,0,137.0,40.0,35.00000,168.000000,43.1,2.288,33,1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.00000,180.000000,32.9,0.171,63,0,-1,-1
764,2,122.0,70.0,27.00000,155.548223,36.8,0.340,27,0,1,1
765,5,121.0,72.0,23.00000,112.000000,26.2,0.245,30,0,1,1
766,1,126.0,60.0,29.15342,155.548223,30.1,0.349,47,1,1,1
767,1,93.0,70.0,31.00000,155.548223,30.4,0.315,23,0,1,1

In [5]:
df_col_not_work = df_data[["is_isolated", "is_lof", "Outcome"]]
df_col_to_work = df_data.drop(columns=["is_isolated", "is_lof", "Outcome"])
df_col_to_work

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148.0,72.0,35.00000,155.548223,33.6,0.627,50
1,1,85.0,66.0,29.00000,155.548223,26.6,0.351,31
2,8,183.0,64.0,29.15342,155.548223,23.3,0.672,32
3,1,89.0,66.0,23.00000,94.000000,28.1,0.167,21
4,0,137.0,40.0,35.00000,168.000000,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.00000,180.000000,32.9,0.171,63
764,2,122.0,70.0,27.00000,155.548223,36.8,0.340,27
765,5,121.0,72.0,23.00000,112.000000,26.2,0.245,30
766,1,126.0,60.0,29.15342,155.548223,30.1,0.349,47
767,1,93.0,70.0,31.00000,155.548223,30.4,0.315,23

In [7]:
robust_scaler = RobustScaler()
robust_scaler.fit(df_col_to_work.values)
df_robust_scaled = robust_scaler.transform(df_col_to_work.values)

In [8]:
df_robust_scaled

array([[ 0.6       ,  0.7654321 , -0.01266201, ...,  0.13186813,
         0.66535948,  1.23529412],
       [-0.4       , -0.79012346, -0.38766201, ..., -0.63736264,
        -0.05620915,  0.11764706],
       [ 1.        ,  1.62962963, -0.51266201, ..., -1.        ,
         0.78300654,  0.17647059],
       ...,
       [ 0.4       ,  0.09876543, -0.01266201, ..., -0.68131868,
        -0.33333333,  0.05882353],
       [-0.4       ,  0.22222222, -0.76266201, ..., -0.25274725,
        -0.06143791,  1.05882353],
       [-0.4       , -0.59259259, -0.13766201, ..., -0.21978022,
        -0.1503268 , -0.35294118]])

In [9]:
standard_scaler = StandardScaler()
standard_scaler.fit(df_robust_scaled)
df_standard_scaled = standard_scaler.transform(df_robust_scaled)
df_standard_scaled

array([[ 0.63994726,  0.86510807, -0.03351824, ...,  0.16629174,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.20616153, -0.52985903, ..., -0.85253118,
        -0.36506078, -0.19067191],
       [ 1.23388019,  2.0158134 , -0.69530596, ..., -1.33283341,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 , -0.0225789 , -0.03351824, ..., -0.91074963,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.14180757, -1.02619983, ..., -0.34311972,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.94314317, -0.19896517, ..., -0.29945588,
        -0.47378505, -0.87137393]])

In [10]:
# Diego Galindo, Francisco Mercado

df_scaled = pd.DataFrame(data=df_standard_scaled, columns=df_col_to_work.columns)
df_final = pd.concat([df_scaled, df_col_not_work.reset_index(drop=True)], axis=1)
df_final

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,is_isolated,is_lof,Outcome
0,0.639947,0.865108,-0.033518,6.655021e-01,-4.634358e-18,0.166292,0.468492,1.425995,1,1,1
1,-0.844885,-1.206162,-0.529859,-1.746338e-02,-4.634358e-18,-0.852531,-0.365061,-0.190672,1,1,0
2,1.233880,2.015813,-0.695306,3.501613e-17,-4.634358e-18,-1.332833,0.604397,-0.105584,1,1,1
3,-0.844885,-1.074652,-0.529859,-7.004289e-01,-7.243887e-01,-0.634212,-0.920763,-1.041549,1,1,0
4,-1.141852,0.503458,-2.680669,6.655021e-01,1.465506e-01,1.548980,5.484909,-0.020496,-1,-1,1
...,...,...,...,...,...,...,...,...,...,...,...
763,1.827813,-0.680125,0.297376,2.145261e+00,2.877840e-01,0.064409,-0.908682,2.532136,-1,-1,0
764,-0.547919,0.010298,-0.198965,-2.451185e-01,-4.634358e-18,0.632039,-0.398282,-0.531023,1,1,0
765,0.342981,-0.022579,-0.033518,-7.004289e-01,-5.125386e-01,-0.910750,-0.685193,-0.275760,1,1,0
766,-0.844885,0.141808,-1.026200,3.501613e-17,-4.634358e-18,-0.343120,-0.371101,1.170732,1,1,1
767,-0.844885,-0.943143,-0.198965,2.101918e-01,-4.634358e-18,-0.299456,-0.473785,-0.871374,1,1,0

In [11]:
df_final.to_csv("../results/3_standardization_final.csv", index=False)

In [12]:
dump(standard_scaler, "../results/3_standard_scaler_instance.joblib")

['../results/3_standard_scaler_instance.joblib']